
# Credit and House Prices Cycles {#Chapter-2}


## Introduction

The Great Recession caused researchers to shift their focus on the narrative of credit, housing market and financial stability. However, the debate on whether house prices have been the main driving source of the credit cycle, or financial conditions (credit) are the main determinants of the house price cycle is still open. One strand of literature has argued that increase in credit supply played a major role in the boom and the subsequent bust in the housing market in the US. Another strand of literature has argued that credit supply itself cannot explain the big swings in house prices and has attributed beliefs and other unobserved characteristics as a major source of house price variations. At the same time, some researchers have argued that credit booms are preceded and sometimes driven by housing booms. The increase in collateral and relaxation of banks' funding constraints leads to an increase in the willingness of the banking sector to provide funding not only to the residential sector but also to commercial real estate as well as overall funding to the businesses.

Most of the work in the literature has considered the relationship between house prices and credit separately, that is, if house prices are affected by credit or changes in house prices affect credit. It is perfectly reasonable to assume that house prices and credit have a dynamic relationship, and the causality does not necessarily run from one variable to another. The novel contribution of this study is to develop a model to jointly examine the two variables of interest: household credit and house prices, and their interaction. In particular, I pay attention to the long-run and short-run movements in credit and house prices and model their joint dynamics. In doing so, I use data from the US and the UK. The methodology I use in this paper to extract transitory and permanent information from non-stationary time series is a decomposition method called Unobserved Components model pioneered by @beveridge_new_1981. The implementation details of the methodology are inspired by @morley_slow_2007 and @huang_rise_2019. This method allows the permanent component to be shown as a random walk with a local growth rate component and the transitory component to be a stationary process with a mean zero. The stationary transitory component configuration is essential to infer meaningful structural linkage between the two variables of interest: household credit and house prices, as non-stationary transitory components do not offer meaningful inferences. This brings up the paper's second novel contribution to the literature. Discovering causality in the structure of a dynamical system from observed time series is a traditional and important problem. By explicitly configuring cross-correlation coefficients on the cyclical components of the two variables, I will be able to examine the predictive ability of the cycles. This would produce a much desired inference for macro-prudential policy implications to stabilize the macroeconomy.

  

Using sample data from the US and the UK, I find interesting and meaningful results from the estimated multivariate correlated unobserved component model. The maximum-likelihood estimates of my proposed correlated multivariate UC model suggest that there is a strong positive correlation between the transitory shock to household credit and the transitory shock to the house prices index. This suggests that a temporary increase in household credit is associated with an increase in house prices above their long-run level. These results support the narrative evidence of the strong relationship between household credit and house prices. More importantly, I also find evidence that lags of the household credit cycle have the predictive ability in forecasting the magnitude of house prices gap above its long-run level by examining the cross-correlation coefficient on the cyclical components. I also find that the trend-cycle decomposition of the two variables of interest captures the recent boom and bust behavior and compares favorably to a univariate trend-cycle decomposition benchmark. In particular, I find that the house prices and household credit were significantly higher than their long-term trend before the financial crisis. Then there was an overreaction during the crisis leading the house price and credit cycle to negative territory, implying that house prices and credit were below their long-run trend. The magnitude of the model's cyclical components for both house price and credit during this time of crisis is significantly higher than that of other univariate decomposition models' such as the HP filter and the VAR unobserved component model.


Finally, my sample data show that the correlation between house price and credit is much higher in the UK than in the US, as shown in Table 1. This help tests the robustness of my model. The plan of the paper is as follows. In section 2, I will discuss the relevant literature branches. In section 3, I will introduce the summary of data and their description. In section 4, I will describe the decomposition methodology using unobserved component model with vector auto-regression (VAR). Specifically, in subsection 4.2, I introduced my contribution to the numerical optimization process in the literature. In section 5, I will go over the model regression results and my interpretation. I will also show cross-countries evidence when using the data from other developed countries. In section 6, I will test the robustness of the model by comparing the results against some traditional methods of analyzing time series data. And lastly, in section 7, I will give my conclusion remark for the model.

  

## Literature Review

There has been an increasing interest in the study of the interaction between credit, speculation, and house prices @mian_house_2011; @mian_credit_2018 , @kishor_forecasting_2020 , @guerrieri_housing_2016, and @davis_housing_2015 have detailed literature reviews on the dynamics between the housing market and credit conditions. I list the four literature branches that study the dynamics of the credit cycles, housing price cycles, and then the critical connection between boom-bust episodes in housing markets and boom-bust episodes in credit markets. There are two approaches to this interaction:(i) The house price cycles generates the credit cycles. (ii) The credit cycles generate the house price cycles.

  

One strand of the literature focuses on how credit cycles are generated. @kiyotaki_credit_1997 modeled the fluctuation of credit conditions due to credit limits and asset prices. The model shows how exogenous shocks can create cyclical fluctuation in credit, asset prices, and real output. @myerson_model_2012 proposed a model of credit cycles generated by moral hazard in dynamic interactions among different generations of financial agents. @guerrieri_housing_2016 used a catastrophe model for credit, in which multiple equilibria are possible due to adverse selection: as credit increases, the composition of borrowers worsens, this can generate a crash in the credit market. @boissay_booms_2016 studied the topic of endogenous boom and bust in the credit market using a dynamic stochastic general equilibrium (DSGE) model, in which moral hazard and asymmetric information may endogenously lead to sudden freezes and crises in the credit market. As for classifying periods of booms and bursts in credit conditions, @alessi_identifying_2018 used a random forest model to identify unsustainable credit growth periods.

  

The second branch of the literature focuses on the dynamics of house price changes. I first look at the generation of momentum in house price changes. Asset prices and valuations tend to vary when information about their performance is available. @thaler_chapter_2005 pointed out that securities with good performance records receive extremely high valuations, and those valuations will return to the mean on average. @hong_unified_1999 suggested a model with information diffuses gradually across the population, and if agents implement simple univariate strategies, their attempts at arbitrage will lead to overreaction at long horizons. @capozza_anatomy_2004 analyzed dynamic properties of markets exhibiting serial correlation and mean reversion. These properties allow prices to overshoot equilibrium (cycles) and permanently diverge from equilibrium. @glaeser_housing_2008 incorporated housing supply elasticity into the analysis of housing prices momentum and showed that the price run-ups of the 1980s were almost exclusively experienced in cities with more inelastic housing supply. @head_search_2014 showed that variation in the time it takes to sell houses induces transaction prices to exhibit serially correlated growth. @glaeser_extrapolative_2017 modeled the leads house prices expectation approximation to display missing features in rational models: momentum at short-run horizon, mean reversion in the long-run horizon, and excess longer-term volatility relative to fundamentals. @kishor_time_2015 studied the US housing market by using a combination of the Unobserved Component model and GARCH model to study the time-varying importance of permanent and transitory housing components in the US housing prices. @knoll_no_2017 constructed a house price index for 14 economies in over 140 years. They argue that real house prices have largely followed a "hockey stick" pattern: fairly consistent for an extended period, followed by a pronounced increase towards the second half of the century with substantial cross-country variation. Furthermore, they say that most of the price increase can be attributed to the increase in the price of land and that house prices have risen faster than income in recent decades. @knoll_return_2016 argued that a rise in house prices coincides with a rise in the price-rent ratio, a fundamental that shows the intrinsic value of housing.

  

Another branch of literature is the one that studies the hypothesis that house price cycles generate credit cycles. The dynamics of houses price on household credit can be viewed through the lens of the borrower balance sheet. @bernanke_agency_1989 developed a neoclassical model of the business cycle in which the condition of borrowers' balance sheets is a source of output dynamics. The mechanism is that higher borrower net worth reduces the agency costs of financing real capital investments. The financial acceleration effects imply that stronger balance sheets due to higher asset prices will lead to a lower cost of borrowing to invest, suggesting that a housing price boom will lead to a boom in credit. @kiyotaki_credit_1997 further incorporated this positive feedback through asset prices and the associated intertemporal multiplier process that affects borrowing capacity and output into their paper. An increase in home equity due to an increase in house prices will allow borrowers to borrow more to finance either personal consumption or more speculation housing investment. @mian_credit_2018 showed that the crash in the housing market and following credit crunch showed the importance of housing prices for household balance sheets and banking sector balance sheets.

  

Some papers have studied the hypothesis that credit cycles generate house price cycles. @agnello_booms_2011 , @agnello_economic_2018 examined different variables likely to create a bubble in housing markets. First is the effect of credit constraints on house prices. @stein_prices_1995 is the first paper to explore the effects of down-payment requirements on house price volatility. The paper highlighted the self-reinforcing effect from house prices to down payments and housing demand back to house prices. If house prices decline, the value of households' collateral declines, depressing housing demand and pushing house prices further down. This multiplier effect can generate multiple equilibria and accounts for the house price boom-bust episodes. The self-reinforcing effect has the same spirit as the transmission mechanism by @kiyotaki_credit_1997. In a recent related paper, @ortalo-magne_housing_2006 showed that income volatility of young households or relaxation of their credit constraints could explain excess volatility of house prices by identifying a powerful driver of the housing market: the ability of young households to afford the down payment on a starter home.

  

Another research branch has also explored the effect of financial innovation or financial liberalization on house prices. @kermani_cheap_2012 proposed a model to emphasize the importance of financial liberalization and its reversal to explain the housing boom and bust. @he_housing_2015 also proposed a model where housing collateralizes loans and house price boom and bust can be generated by financial innovation because the liquidity premium on housing is non-monotone in the loan-to-equity ratio. @huo_financial_2016 had a model with heterogenous households, housing, and credit constraints and also showed that financial shocks can generate large drops in housing prices. @favilukis_international_2012 studied the impact of systemic changes in housing finance: changes in housing collateral requirements and the change in borrowing costs (the spread of mortgage rates over risk-free security) on how these factors affect risk premiums in housing markets, and how those risk premiums, in turn, affect home prices. @favilukis_macroeconomic_2017 developed a quantitative general equilibrium model with housing and collateral constraints to explore what drives fluctuations in house prices to rent ratio. They propose that relaxation of financing constraints leads to a significant boom in house prices. Furthermore, the boom in house prices is entirely the result of a decline in the housing risk premium. @mian_credit_2018 showed that speculation is a critical channel through which credit supply expansion affects the housing cycle.

  

After the financial crisis, there has also been an explosion of interest in the effect of credit expansion on house prices. @justiniano_credit_2019 argued that loosening the collateral requirements alone cannot explain the recent housing boom in the US, but there must have been an expansion in the credit supply. The authors argued that house prices rose from 2000 to 2007 without an expansion of leverage. The cause of the housing boom before the recession was an increase in credit supply or available funds rather than an increase in leverage. The rates of mortgages to real estate remained constant. This contradicts the popular view that attributes the housing boom to looser borrowing constraints associated with lower collateral requirements, which would shift the demand for credit. In short, the increase in the supply of credit was the cause of the housing boom. Beyond 2007, the paper argues that there was an increase in collateralizing houses relative to available funds or that available funds for lending decreased, leading to a rise in mortgage rates and a collapse of house prices. More interestingly, in a series of papers, Jorda, Schularick, and Taylor have studied the interplay between credit, house price, and economic performance. @schularick_credit_2012 created new data sets for 14 developed countries over 140 years and showed how credit growth is a powerful predictor of financial crises. @jorda_great_2016 claimed that mortgage lending booms were loosely related to financial crises before WWII but have become a more important predictor of financial fragility. The share of mortgages on banks' balance sheets doubled in the later half of the twentieth century, driven by household mortgage lending. Household debt to asset ratios have risen substantially in the study's many countries. Financial stability risks have been linked to real estate lending booms. @jorda_betting_2015 claims that there has been an increase in the mentality of "bets on the house" in the past century. Mortgage credit has risen dramatically as a share of banks' balance sheets from about one-third at the beginning of the last century to about two-thirds nowadays. They use a novel IV local projection method to demonstrate that loose monetary conditions lead to booms in real estate and house price bubbles. These, in turn, lead to a higher risk of financial crises. Mortgage booms and house price bubbles have been closely associated with a higher likelihood of a financial crisis. @jorda_macrofinancial_2017 claimed that a century-long and stable ratio of credit to GDP gave way to rapid financialization and surging leverage in the last forty years. This coincides with a shift in foundational macroeconomic relationships. More financialized economies exhibit more tail risk and tighter real-real and real-financial correlations, including the credit and real estate correlation. The paper also shows that real house prices and mortgages in 17 sample countries display a "hockey stick" pattern. They both stay stable for a long time before ticking up drastically at the end of the sample. It can be shown that house price growth and mortgage growth generally co-move. @favara_credit_2015 showed an expansion in mortgage credit has significant effects on house prices using a spatial IV strategy with the US branching deregulation between 1994 and 2005 as an instrument for credit. The treated banks' credit expansion led to increases in housing demand. @di_maggio_credit-induced_2017 showed that a credit expansion could generate a boom and bust in house prices and real activity. The paper uses the exploitation of the same federal deregulation in preemption of local laws against predatory lending in 2004 to gauge the effectiveness of the supply of credit on the real economy.

  

However, the debate on whether house prices have been the main driving source of the credit cycle or financial conditions (credit) are the main driving force of the house price cycle is still open. In this paper, I will use a dynamic model to explain the relationship between these two variables in both the short-term and long-term.

