## Conclusion
My study is based on the idea that house prices and credit are jointly determined, affecting each other in the short and long run. I decompose the movements of the two variables of interest into a permanent and transitory component. The correlations among the cyclical components support the idea that the rise of house prices is associated with an increase in household credit above its long-run trend. My multivariate model captures the dynamic features of the household credit and house prices series and performs better than univariate benchmarks in capturing the boom and bust during the last two decades. Additionally, employing cross-correlation effects on the transitory components of the two series allows me to test the predictive ability of the cyclical components and find evidence to support that a house prices gap can positively predict a household credit gap. These findings suggest macroprudential policy implications since house prices are increasingly becoming a more important topic.

Further development for this paper should include studying on policy implications of credit and house price gaps with high magnitudes. More robust optimal constraints on parameters to ensure stability and model robustness rather than an ad-hoc approach to selecting weights. Lastly, it would be meaningful to link the information from this paper's causal effect coefficients estimates to the bigger picture regarding macroprudential policy models that includes housing price and household credit, such as systemic financial stability model^[@alessi_identifying_2018] or house price growth-at-risk models^[@deghi_predicting_2020].
