## Data Description

The model sample periods include quarterly data from 1970:Q4 to 2017:Q4 across 43 countries.^[The list of countries with data available are: Argentina, Austria, Australia, Belgium, Brazil, Canada, Switzerland, Chile, China, Colombia, Czech Republic, Germany, Denmark, Spain, Finland, France, United Kingdom, Greece, Hong Kong SAR, Hungary, Indonesia, Ireland, Israel, India, Italy, Japan, Korea, Luxembourg, Mexico, Malaysia, Netherlands, Norway, New Zealand, Poland, Portugal, Russia, Saudi Arabia, Sweden, Singapore, Thailand, Turkey, United States, and South Africa.] The sample periods were chosen based on the availability of systemic crisis data and total credit to GDP ratio data. The primary source of the credit data comes from the Bank of International Settlement (BIS). The credit variable is measured as total credit to the private non-financial sector as a percentage of GDP.^[Source of the data could be accessed here: https://www.bis.org/statistics/totcredit/credpriv_doc.pdf] 

Regarding data for dating systemic crises, there is no single consensus source of database. I follow the literature and use the crisis dates reported in the European Systemic Risk Board crisis data set [@lo_duca_new_2017] for countries in the EU and [@laeven_systemic_2013] for the rest of the world. The systemic crisis dates are available from after WWII. However, the first systemic crisis did not happen until the early 1970s. 

There are three types of crises: banking, currency, and debt crises, all of which could lead to a systemic crisis. A crisis can be labeled as systemic when certain conditions are met, such as significant signs of financial distress in the banking system, bank runs, and significant policy intervention measurements are imposed. The authors also consulted with subject matter experts in each country to determine the dates and details of the systemic crises.

While the credit data is available until 2021:Q3, my systemic crisis data stopped at 2017:Q4. Therefore, I will limit my analysis till 2017:Q4. I will also omit periods of countries with shorter measurements of credit.

<!--**Insert descriptive statistics table here** -->

